version: "2.2"

services:
  elasticsearch:
    container_name: "esd_elasticsearch-8.3.3"
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file: [".env"]
    environment:
      - "cluster.name=esd"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.http.ssl.certificate=$ELASTICSEARCH_CERTS_DIR/localhost/localhost.crt"
      - "xpack.security.http.ssl.key=$ELASTICSEARCH_CERTS_DIR/localhost/localhost.key"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.certificate=$ELASTICSEARCH_CERTS_DIR/localhost/localhost.crt"
      - "xpack.security.transport.ssl.key=$ELASTICSEARCH_CERTS_DIR/localhost/localhost.key"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "xpack.license.self_generated.type=trial"
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./cert-bundle:$ELASTICSEARCH_CERTS_DIR"
      - "./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "esdata-8.3:/usr/share/elasticsearch/data"
    ports: ["19200:9200"]

  kibana:
    container_name: "esd_kibana-8.3.3"
    image: "docker.elastic.co/kibana/kibana:8.3.3"
    env_file: [".env"]
    environment:
      - "ELASTICSEARCH_HOSTS=https://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=$KIBANA_ES_USERNAME"
      - "ELASTICSEARCH_PASSWORD=$KIBANA_ES_PASSWORD"
      - "ELASTICSEARCH_SSL_KEY=$KIBANA_CERTS_DIR/localhost/localhost.key"
      - "ELASTICSEARCH_SSL_CERTIFICATE=$KIBANA_CERTS_DIR/localhost/localhost.crt"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$KIBANA_CERTS_DIR/ca/ca.crt"
      - "ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate"
      - "XPACK_REPORTING_CAPTURE_BROWSER_TYPE=chromium"
      - "XPACK_REPORTING_KIBANASERVER_PORT=8080"
      - "XPACK_REPORTING_KIBANASERVER_PROTOCOL=https"
      - "XPACK_REPORTING_KIBANASERVER_HOSTNAME=web"
      - "XPACK_REPORTING_ENCRYPTIONKEY=$XPACK_REPORTING_ENCRYPTIONKEY"
      - "XPACK_SECURITY_ENCRYPTIONKEY=$XPACK_SECURITY_ENCRYPTIONKEY"
      - "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=$XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY"
      - "XPACK_REPORTING_CAPTURE_BROWSER_CHROMIUM_DISABLESANDBOX=true"
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"
      - "./cert-bundle:$KIBANA_CERTS_DIR"
    ports: ["15601:5601"]

volumes:
  esdata-8.3:
    driver: "local"
